/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moonsolid.sc;

public class ServerApp {
  public static void main(String[] args) {
    System.out.println("서버 스케쥴관리 시스템입니다.");

  }
}
